spring:
  application:
    name: asupg-service

server:
  servlet:
    context-path: /api/asupg-service
  port: 8080

azure:
  cosmos:
    database: ${azure.cosmos.database}
    endpoint: ${azure.cosmos.endpoint}
    key: ${azure.cosmos.key}
    container-companies: Companies

asupg:
  billing:
    free-period: 1 # Amount of years for which companies are free to use the service
    monthly-rate: 100000 # Default monthly rate which will be used unless specified otherwise

security:
  jwt:
    expireInMinutes: 15
    secret: a;slkdfjanva;lsejtnakjsnvjal;sj;fd